[package]
name = "crud-rocket"
version = "0.1.0"
authors = ["ponchione <mitchell.ponchione@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"